# This is a basic workflow to help you get started with Actions
name: 'MacOS Build'

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        node-version: [16.x]

    # The type of runner that the job will run on
    runs-on: macos-11

    steps:
          
    - name: Install Dependencies
      run: npm i
    - name: Check lint
      run: npm run lint
    - name: Build the app
      run: npm run electron:build
